import Foundation
import SwiftUI

/// The app's own UI language — separate from `ScanResultLanguage`, which
/// only controls the language AI-generated scan/search text is written in.
/// Currently Korean (the app's native-written language, always available
/// with no translation lookup) and English.
///
/// Decided by the device, not by a picker in this app. Settings used to
/// carry its own "앱 언어" choice, which meant a person who had already
/// told iOS what language they read had to tell this app too — and could
/// end up with the two disagreeing. iOS relaunches an app when its
/// language changes, so this is also constant for the lifetime of a
/// process, which is what let the whole runtime language-switching
/// apparatus (an observable holding the choice, and a `.id()` remount of
/// the entire view tree at the app root) go away with it.
enum AppLanguage: String {
    case korean
    case english

    /// Resolved from the device's preferred languages each time it is
    /// asked — there is no stored copy to keep in sync. Anything that
    /// isn't Korean resolves to English, this app's only other
    /// translation, rather than to Korean: someone reading neither is far
    /// likelier to get by in English.
    static func current() -> AppLanguage {
        (Locale.preferredLanguages.first ?? "").hasPrefix("ko") ? .korean : .english
    }
}

extension String {
    /// This Korean UI string, translated to the current `AppLanguage` —
    /// falls back to the Korean original (this string itself) when the
    /// app language is Korean, or no translation exists for it yet, so
    /// every UI string can safely call this even before full translation
    /// coverage. Reads `AppLanguage.current()` directly, so it works from
    /// any context: a `View.body`, a plain service/error type, a
    /// #Preview. Nothing has to re-render on a language change, because
    /// iOS relaunches the app when the device language changes.
    var localized: String {
        guard AppLanguage.current() == .english, let translated = Localization.englishTranslations[self] else {
            return self
        }
        return translated
    }
}

/// English translations for every Korean UI string in the app, keyed by
/// that exact Korean source text. Deliberately a flat dictionary (not a
/// String Catalog / `.xcstrings` resource) — this project has no Xcode to
/// generate or validate one against, and a plain Swift literal is
/// something this environment's own tooling (brace/paren balance,
/// duplicate-declaration checks) can actually verify.
///
/// A handful of entries translate to an empty string or a short fragment
/// on purpose — they're the constant half of a call site built as
/// `"고정 문구".localized + dynamicValue` (splitting a Korean sentence
/// that has interpolation or an escaped quote in it, since those can't be
/// a single dictionary key). Search the call sites for the exact Korean
/// text if a translation here looks incomplete on its own.
enum Localization {
    static let englishTranslations: [String: String] = [
        "애플 지도 서버에 연결하지 못했습니다.": "Couldn't reach Apple Maps.",
        "애플 지도 요청이 너무 잦습니다. 잠시 뒤 다시 시도해주세요.": "Too many Apple Maps requests. Please try again shortly.",
        "이 백업을 가져올까요?": "Import this backup?",
        "이 기기에 없는 장소는 추가하고, 백업 쪽이 더 나중에 수정된 장소는 그 내용으로 바꿉니다. 백업에 없는 장소는 그대로 둡니다.":
            "Places this device is missing are added, and places the backup edited more recently replace the copies here. Places the backup doesn't contain are left alone.",
        "이 백업에서 바뀐 것이 없습니다.": "Nothing in this backup changed anything here.",
        "곳 추가": " added",
        "곳 갱신": " updated",
        "\"iCloud에 자동 보관\"은 게시판·장소·사진 전체의 사본을 본인의 iCloud 계정 안 이 앱 전용 공간에 저장해, 기기를 바꾸거나 앱을 다시 설치했을 때 복구할 수 있게 합니다. 끄면 이미 저장된 사본도 삭제됩니다. \"전체 백업\"은 같은 내용을 직접 고른 파일로 저장하며, 복원하면 이 기기에 없는 장소는 추가하고 백업 쪽이 더 나중에 수정된 장소는 그 내용으로 바꿉니다. 백업에 없는 장소는 그대로 둡니다.":
            "\"Keep a copy in iCloud\" stores every board, place and photo in this app's own space inside your iCloud account, so you can recover them on a new device or after reinstalling. Turning it off also deletes the copy already stored. \"Full Backup\" saves the same contents to a file you choose; restoring one adds the places this device is missing and replaces the ones the backup edited more recently. Places the backup doesn't contain are left alone.",
        "iCloud에서 이전 백업을 찾아 게시판과 장소를 가져왔습니다.": "Found an earlier backup in iCloud and brought its boards and places in.",
        "Google 지도나 네이버 지도에서 장소를 공유하면 바로 카드가 됩니다. 별도 설정 없이 지금 바로 쓸 수 있어요.": "Share a place from Google Maps or Naver Map and it becomes a card right away — no setup needed to start.",
        "곧 영업 종료": "Closing soon",
        "공유로 바로 담기": "Save it by sharing",
        "나중에": "Later",
        "나중에 설정 탭에서 언제든 등록할 수 있습니다.": "You can add it any time from the Settings tab.",
        "아직 방문 기록이 없습니다.": "No visits recorded yet.",
        "영업 종료": "Closed",
        "영업 중": "Open now",
        "오늘 방문": "Visited today",
        "사진에서 방문일 찾기": "Find Visit Dates in Photos",
        "현장에서 찍은 사진이 없습니다. 사진을 먼저 추가해주세요.": "There are no photos taken on site. Add a photo first.",
        "사진에 촬영 날짜가 없습니다.": "The photos carry no capture date.",
        "사진의 촬영 날짜는 이미 모두 기록돼 있습니다.": "Every capture date from these photos is already recorded.",
        "사진이 이 장소에서 멀리 떨어진 곳에서 찍혔습니다.": "The photos were taken far away from this place.",
        "사진에서 방문 날짜 ": "Found ",
        "개를 찾았습니다.": " visit date(s) from photos.",
        "오늘 방문함": "Visited today",
        "지금 설정하기": "Set it up now",
        "개 중 ": " in this list, ",
        "개를 가져옵니다. 구글이 공유 링크에 담아 보내는 최대 개수입니다.": " will be imported — that is the most Google puts in a shared link.",
        "이 목록 ": "Of the ",
        "Google Maps · ": "Google Maps · ",
        "가져온 장소는 Google에서 하나씩 확인해 평점·연락처·영업시간·사진까지 채웁니다. 장소 수만큼 본인의 Google Places API 키가 사용됩니다.": "Each imported place is checked against Google one by one to fill in its rating, contacts, hours, and photo. That uses your own Google Places API key once per place.",
        "가져온 장소를 Google에서 하나씩 확인하는 중입니다. 중단해도 이미 확인된 장소는 그대로 남습니다.": "Checking the imported places against Google, one at a time. Stopping keeps whatever has already been confirmed.",
        "가져올 장소 (": "Places to import (",
        "개)": ")",
        "게시판 이름": "Board name",
        "공유한 목록": "Shared list",
        "공유한 목록 가져오기": "Import Shared List",
        "만들 게시판": "Board to create",
        "이 목록 가져오기": "Import this list",
        "중단": "Stop",
        "카드 검색": "Search cards",
        "카드 삭제": "Delete card",
        "카테고리 검색": "Search categories",
        "카테고리별 보기": "Browse by Category",
        " API 키가 저장되었습니다.": " API key saved.",
        " 정보를 채웠습니다.": " filled in.",
        "\" 근처 100m 이내에서 찾지 못했습니다.": "\" — nothing found within 100m of that address.",
        "\"(으)로 병합": "\" merge",
        "\"(으)로 보관해 두었으니 덮어쓰지 않았습니다. 백업에서 복원하거나 지원에 문의해주세요.": "\" and was not overwritten. Restore from a backup, or get in touch for help.",
        "\"(으)로 보이는데, 현재 이름 \"": "\", but the current name is \"",
        "\"과 다릅니다. 이름을 바꿀까요?": "\". Change the name?",
        "\"을 삭제할까요?": "\"?",
        "\"지도\" 탭에서 Naver 지도를 선택했을 때만 사용됩니다. NAVER Cloud Platform Maps 애플리케이션의 Client ID이며, Secret은 필요 없습니다. 지도가 뜨는 페이지는 이 앱이 아니라 mrnoh99.github.io에서 불러오므로, 콘솔의 해당 Application 설정에서 Web 서비스 URL에 반드시 \"mrnoh99.github.io\"를 등록해야 합니다 — 등록하지 않으면 Client ID는 통과해도 지도 타일이 전부 실패합니다.": "Only used when Naver Maps is selected in the \"Map\" tab. This is the Client ID of a NAVER Cloud Platform Maps application — no Secret is needed. The map page itself is loaded from mrnoh99.github.io rather than from this app, so you must register \"mrnoh99.github.io\" as the Web Service URL in that Application's console settings — without it, the Client ID will validate but every map tile will still fail to load.",
        "\"지도에서 열기\"로 최근에 연 카드예요. 방금 공유한 사진을 이 카드에 추가하고, AI로 읽어 비어 있는 이름·주소를 채웁니다.": "This card was recently opened via \"Open in Map\". The photo you just shared will be added to it, and AI will read it to fill in a blank name/address.",
        "\"지도에서 열기\"로 최근에 연 카드예요. 방금 공유한 지도 링크의 정보(이름·주소·좌표)를 이 카드에 채웁니다.": "This card was recently opened via \"Open in Map\". Info from the map link you just shared (name, address, coordinates) will be filled into it.",
        "(키 없음)": "(no key)",
        ")가 발견되어 적용하지 않았습니다. 한 장소가 나온 사진으로 다시 시도해주세요.": ") were found, so nothing was applied. Try again with a photo showing one place.",
        ")가 발견되어 정보는 채우지 않았습니다.": ") were found, so no info was filled in.",
        "+ 링크 추가": "+ Add link",
        "+ 방문 날짜 추가": "+ Add visit date",
        "+ 요일 추가": "+ Add day",
        "2026년 4월": "April 2026",
        "AI 없이 Google Places API로 이 장소의 영업시간·평점·전화번호·웹사이트 등 비어 있는 항목만 다시 확인합니다. 실제 사진이 없으면(글자판독용으로 올린 스크린샷만 있어도) Google의 대표 사진도 가져옵니다.": "Without AI, re-checks this place's hours, rating, phone, website, and other blank fields straight from the Google Places API. Also pulls Google's own cover photo if there's no real photo yet (even if the only thing there is a screenshot uploaded just for text recognition).",
        "AI 없이 Naver 지역검색 API로 이 장소의 전화번호·웹사이트·카테고리 등 비어 있는 항목만 다시 확인합니다. 평점·영업시간·사진은 Naver 지역검색이 제공하지 않아 채워지지 않습니다.": "Without AI, re-checks this place's phone, website, category, and other blank fields via the Naver local search API. Rating, hours, and photos aren't filled in, since Naver's local search doesn't provide them.",
        "AI가 읽은 정보를 채웠습니다.": "Filled in what AI read.",
        "AI가 태그를 제안했습니다": "AI suggested some tags",
        "AI가 찾은 장소를 검토·수정하세요. \"Google에서 검색\"으로 정확한 주소·평점·연락처를 채울 수 있습니다.": "Review or edit the places AI found. Use \"Search on Google\" to fill in the exact address, rating, and contact info.",
        "AI로 장소 분석하기 (": "Analyze photos with AI (",
        "AI로 정보 읽어오기": "Read info with AI",
        "API 오류 (": "API error (",
        "API 키": "API Key",
        "API 키 저장 방식": "How API keys are stored",
        "Apple 지도": "Apple Maps",
        "Apple 지도 공유": "Shared from Apple Maps",
        "GPS로 촬영위치찾기": "Find Location by Photo GPS",
        "사진 위치로 보기": "View Photo Location",
        "이름으로 찾기": "Search by Name",
        "Google API 키가 저장되었습니다.": "Google API key saved.",
        "Google API 키가 필요합니다": "A Google API key is required",
        "Google Maps에서 열기": "Open in Google Maps",
        "Google 지도, Naver 지도, Trip Advisor 등 이 장소의 페이지 링크를 추가해두면 상세보기에서 바로 열 수 있습니다.": "Add links to this place's page on Google Maps, Naver Map, Trip Advisor, and the like, and open them straight from the detail view.",
        "Google 지도를 불러오지 못했습니다 — 설정의 API 키를 확인해주세요.": "Couldn't load Google Maps — please check the API key in Settings.",
        "Google 지도에서 확인됨": "Confirmed on Google Maps",
        "Google/Naver/Apple에서 장소 확정": "Confirm Place via Google/Naver/Apple",
        "Apple에서 검색": "Search on Apple",
        "Google에서 검색": "Search on Google",
        "Google에서 새로 채울 정보를 찾지 못했습니다.": "Found nothing new to fill in from Google.",
        "Google에서 새로고침": "Refresh from Google",
        "Google에서 자동으로 확인한 장소 ": "Places automatically confirmed on Google: ",
        "Naver Client ID가 필요합니다": "A Naver Client ID is required",
        "Naver Maps Client ID가 저장되었습니다.": "Naver Maps Client ID saved.",
        "Naver 지도 페이지에 연결할 수 없습니다 — 인터넷 연결을 확인해주세요.": "Couldn't connect to the Naver Maps page — please check your internet connection.",
        "Naver 지도 스크립트를 불러오지 못했습니다.": "Failed to load the Naver Map script.",
        "Naver 지도가 이 Client ID를 거부했습니다 — 설정에서 확인해주세요.": "Naver Map rejected this Client ID — check it in Settings.",
        "Naver 지도를 불러오지 못했습니다 — 설정의 Client ID를 확인해주세요.": "Couldn't load Naver Map — check your Client ID in Settings.",
        "Naver 지도에서 확인됨": "Confirmed on Naver Map",
        "Naver 검색 API 정보가 저장되었습니다.": "Naver Search API credentials saved.",
        "Naver에서 검색": "Search on Naver",
        "Naver에서 새로 채울 정보를 찾지 못했습니다.": "Found nothing new to fill in from Naver.",
        "Naver에서 새로고침": "Refresh from Naver",
        "PinSpots 백업 파일이 아닙니다.": "This isn't a PinSpots backup file.",
        "PinSpots는 사용자가 등록한 API 키로 직접 Google/Naver/AI 서비스를 호출합니다(BYOK). 키는 iCloud와 동기화되지 않으며 이 기기에만 저장됩니다.": "PinSpots calls Google/Naver/AI services directly using the API keys you register (BYOK). Keys are not synced via iCloud and are stored only on this device.",
        "Unsplash 검색": "Unsplash Search",
        "iCloud에서 복원됨": "Restored from iCloud",
        "iOS 키체인 (기기 내)": "iOS Keychain (on-device)",
        "✅ 방문 (": "✅ Visited (",
        "⭐ 즐겨찾기 (": "⭐ Favorites (",
        "가격대": "Price level",
        "가져오기": "Import",
        "가져올 내용": "What will be imported",
        "같은 장소가 두 번 이상 저장된 것으로 보이는 ": "Found ",
        "개": "",
        "개 그룹을 찾았습니다. 남길 카드를 고른 뒤 병합하세요 — 나머지가 가진 정보(연락처·링크·사진·방문 기록·장소확정 등)는 남는 카드에 빠짐없이 옮겨진 뒤 삭제됩니다.": " group(s) that look like the same place saved more than once. Pick the card to keep, then merge — everything the others hold (contacts, links, photos, visit history, verified-place status, and the rest) is moved onto the kept card before they're deleted.",
        "개 장소를 저장하지 못했습니다. 기기 저장 공간을 확인한 뒤 다시 시도해주세요.": " place(s) couldn't be saved. Check your device's available storage and try again.",
        "개 삭제": " selected — Delete",
        "개 선택)": " selected)",
        "개 선택됨": " selected",
        "개 장소를 삭제할까요?": " place(s)?",
        "개 카테고리를 이 이름으로 합칩니다.": " categories will be merged into this name.",
        "갤러리": "Gallery",
        "갤러리 · ": "Gallery · ",
        "갤러리에서 사진 선택 (여러 장 가능)": "Choose photos from gallery (multiple allowed)",
        "검색 결과가 없습니다.": "No search results.",
        "게시물을 캡처(스크린샷)해서 \"장소 추가\"의 사진 선택으로 다시 추가해주세요.": "Capture (screenshot) the post and add it again using photo picker in \"Add Place\".",
        "게시판": "Board",
        "게시판 가져오기": "Import Board",
        "게시판 수정": "Edit Board",
        "게시판 이동": "Move Board",
        "게시판이 없습니다": "No Boards",
        "경도": "Longitude",
        "공유": "Share",
        "공유로 사진 가져오기": "Importing shared photos",
        "공유한 링크를 추가할 게시판": "Board to add the shared link to",
        "공유한 링크에서 장소 이름을 찾지 못했습니다.": "Couldn't find a place name in the shared link.",
        "공유한 링크에서 장소 정보를 찾지 못했습니다.": "Couldn't find place info in the shared link.",
        "공유한 링크에서는 \"": "The shared link looks like \"",
        "공유한 사진을 추가할 게시판": "Board to add the shared photo to",
        "공유한 사진": "Shared photo",
        "공유한 정보": "Shared info",
        "공유한 정보를 확인하는 중…": "Checking the shared info…",
        "공유한 지도 링크의 위치가 카드의 기존 좌표와 100m 이상 떨어져 있어 좌표는 바꾸지 않았습니다.": "The shared map link's location is more than 100m from the card's existing coordinates, so they weren't changed.",
        "공유한 지도 정보를 카드에 채웠습니다.": "Filled in the shared map info on the card.",
        "관광 정보": "Visitor info",
        "구글 지도 공유": "Google Maps share",
        "구글 지도 스크린샷": "Google Maps screenshot",
        "그 파일에서 복원하지 못했습니다.": "Couldn't restore from that file.",
        "기기의 위치 서비스가 꺼져 있지 않은지 확인하거나, 위치 신호를 받을 수 있는 곳에서 다시 시도해주세요.": "Check that Location Services is turned on for this device, or try again somewhere you can get a location signal.",
        "기본 정보": "Basic Info",
        "기존 게시판·장소는 그대로 두고, 새 게시판으로 추가됩니다.": "Existing boards and places are left as-is — this is added as a new board.",
        "기준: ": "From: ",
        "기준: 현재 위치": "From: Current Location",
        "내 평점 (0~5)": "My rating (0-5)",
        "내보내기": "Export",
        "네이버 지도 공유": "Naver Map share",
        "네이버 지도 스크린샷": "Naver Map screenshot",
        "네이버 지도에서 공유받은 장소는 Google 대신 이 API로 검증합니다. 위 \"Naver 지도 표시\"와는 별개의 애플리케이션입니다 — NAVER Cloud Platform 콘솔(console.ncloud.com)에서 Menu → All Services → Application Services → NAVER API HUB로 들어가 Application을 등록할 때 \"검색\" API를 선택하고, 등록된 Application의 \"인증 정보\"에서 Client ID/Secret을 확인해 입력하세요. 설정하지 않으면 지금처럼 Google로 검증합니다.":
            "A place shared from Naver Map is verified with this API instead of Google. Separate application from \"Naver Map Display\" above — in the NAVER Cloud Platform console (console.ncloud.com), go to Menu → All Services → Application Services → NAVER API HUB, register an Application selecting the \"Search\" API, then check the Client ID/Secret under that Application's \"Authentication Information\" and enter them here. If unset, verification falls back to Google as before.",
        "네트워크 오류: ": "Network error: ",
        "다시 갈래요": "Would revisit",
        "다시 방문 의향": "Would revisit?",
        "다시 안 갈래요": "Wouldn't revisit",
        "다음": "Next",
        "다른 장소예요 — 새 카드로 추가": "This is a different place — add as a new card",
        "닫기": "Close",
        "대조할 장소 주소가 없어 사진의 위치 정보만 사용합니다.": "There's no place address to compare against, so only the photo's location is used.",
        "대표사진": "Cover Photo",
        "대표사진으로 설정": "Set as Cover Photo",
        "데이터": "Data",
        "데이터 처리 오류: ": "Data processing error: ",
        "도쿄 봄 여행": "Tokyo Spring Trip",
        "되돌릴 수 없습니다.": "This can't be undone.",
        "둘 다 비우면 좌표가 삭제됩니다. 하나만 채워지면 원래 값이 그대로 유지됩니다. \"주소로 좌표 확인\"은 AI 없이 Google Places로 위 주소를 좌표로 바꿔줍니다 — 상세보기의 \"지도에서 열기\"로 정확한 주소를 먼저 확인한 뒤 여기 채우고 눌러보세요. \"위치정보에 사진 GPS 사용\"을 켜두면, 위도·경도가 비어 있을 때 새로 추가하는 사진의 GPS를 좌표로 저장합니다(주소와 100m 이상 차이 나면 저장하지 않고 알려드립니다). 이미 채워져 있으면 새 사진이 그 위치에서 찍힌 게 맞는지만 확인합니다.":
            "Leaving both blank removes the coordinate. Filling in only one keeps the original value. \"Find Coordinates from Address\" turns the address above into coordinates via Google Places, no AI needed — first confirm the exact address using \"Open in Map\" in the detail view, then fill it in here and tap. Turning on \"Use Photo GPS for Location Info\" saves a newly added photo's GPS as the coordinates when latitude/longitude are blank (unless it's more than 100m from the address, in which case you're told and nothing is saved). If they're already filled in, this only checks whether the new photo looks like it was actually taken there.",
        "또는 파일에서": "Or from a file",
        "로 대체해 가져왔습니다.": " answered as a fallback.",
        "리뷰 ": "",
        "리뷰 수": "Review count",
        "마감 ": "Closes ",
        "마감 시간": "Closing time",
        "마지막 백업: ": "Last backup: ",
        "만들기": "Create",
        "매일": "Daily",
        "매주": "Weekly",
        "먼저 게시판을 만들고, 그 안에 장소 카드를 추가해보세요.": "Create a board first, then add place cards to it.",
        "먼저 홈에서 게시판을 만들어주세요.": "Please create a board on Home first.",
        "메모": "Memo",
        "메모 (선택)": "Memo (optional)",
        "메모 없음": "No memo",
        "모델": "Model",
        "모두 병합했습니다": "Everything Merged",
        "모든 카드": "All Cards",
        "모름": "Unsure",
        "무료": "Free",
        "미쉐린 별점, TripAdvisor Travelers' Choice, 블루리본서베이 등 제3자가 부여한 인증을 적어둡니다.": "Note third-party recognitions here — Michelin stars, TripAdvisor Travelers' Choice, Blue Ribbon Survey, and the like.",
        "방문 날짜": "Visit date",
        "방문 날짜 삭제": "Delete visit date",
        "방문함": "Visited",
        "백업 폴더 선택…": "Choose Backup Folder…",
        "백업 폴더를 설정하지 못했습니다.": "Couldn't set the backup folder.",
        "백업에서 복원": "Restore from Backup",
        "백업을 저장하지 못했습니다.": "Couldn't save the backup.",
        "백업을 저장했습니다.": "Backup saved.",
        "백업을 준비하지 못했습니다.": "Couldn't prepare the backup.",
        "변경": "Change",
        "병합": "Merge",
        "병합 (": "Merge (",
        "병합할 카테고리 이름": "Name for the Merged Category",
        "복원": "Restore",
        "부제목 (예: 2026년 4월 · 도쿄)": "Subtitle (e.g. April 2026 · Tokyo)",
        "붙여넣은 텍스트 확인": "Check Pasted Text",
        "비어있는 게시판 \"": "Delete the empty board \"",
        "사용자가 취소했습니다.": "Cancelled by user.",
        "사용자 보드": "My Boards",
        "사진": "Photos",
        "사진 가져오기": "Import Photo",
        "사진 삭제": "Delete Photo",
        "사진 더 추가": "Add More Photos",
        "사진 선택": "Choose Photos",
        "사진 스캔 시 이 순서대로 시도합니다. 키가 등록되지 않은 제공자는 건너뜁니다.": "Tried in this order for photo scanning. A provider with no key registered is skipped.",
        "사진 위치": "Photo Location",
        "사진 추가": "Add Photo",
        "사진에서 정보 수집": "Collect Info from Photos",
        "사진에서 여러 장소(": "Several places found in the photo (",
        "사진에서 장소 정보를 찾지 못했습니다.": "Couldn't find place info in the photo.",
        "사진에서 새로 채울 정보를 찾지 못했습니다.": "Found nothing new to fill in from the photo.",
        "사진에서는 \"": "The photo looks like \"",
        "사진은 저장 시 카드에 추가됩니다. \"AI로 정보 읽어오기\"는 비어 있는 이름·주소를 채우는데, 사진에서 여러 장소가 발견되면 적용하지 않고 알려드리고, 이름이 바뀌는 경우엔 확인 후 적용됩니다.": "The photo is added to the card when you save. \"Read Info with AI\" fills in a blank name/address — if several places are found in the photo, nothing is applied and you're told; if the name would change, it's applied only after you confirm.",
        "사진을 미리 볼 수 없습니다.": "This photo can't be previewed.",
        "사진을 카드에 추가했습니다.": "Added the photo to the card.",
        "사진을 카드에 추가했습니다. (장소 정보는 찾지 못했습니다.)": "Added the photo to the card. (No place info was found.)",
        "사진을 카드에 추가했습니다. (정보 읽기 실패: ": "Added the photo to the card. (Failed to read info: ",
        "사진을 카드에 추가했습니다. 사진에서 여러 장소(": "Added the photo to the card. Several places were found in the photo (",
        "사진의 위치 정보가 인식된 장소 주소와 너무 멀어 사진 위치는 사용하지 않았습니다.": "The photo's location was too far from the recognized place's address, so it wasn't used.",
        "사진의 위치 정보로 좌표를 저장했습니다.": "Saved this location from the photo's GPS as the coordinates.",
        "삭제": "Delete",
        "상태": "Status",
        "새 게시판": "New Board",
        "샘플 카페": "Sample Cafe",
        "서울시 강남구": "Gangnam-gu, Seoul",
        "선택": "Select",
        "선택한 ": "Selected ",
        "선택한 장소": "Selected Places",
        "선택한 폴더에 백업했습니다.": "Backed up to the chosen folder.",
        "설정": "Settings",
        "설정 안 함": "Not set",
        "설정 열기": "Open Settings",
        "설정에서 AI 제공자 키를 등록하면 이 기능을 사용할 수 있습니다.": "Register a key for an AI provider in Settings to use this feature.",
        "설정에서 API 키를 먼저 등록해주세요.": "Please register an API key in Settings first.",
        "설정에서 Google Places API 키를 등록해주세요.": "Please register a Google Places API key in Settings.",
        "설정에서 Naver 지도 표시용 NCP Client ID를 등록해주세요.": "Please register an NCP Client ID for Naver Map display in Settings.",
        "수상/인증": "Awards",
        "수정": "Edit",
        "수정한 날짜: ": "Edited: ",
        "수정할 장소를 선택하세요": "Select places to edit",
        "쉼표로 구분": "Comma-separated",
        "식당": "Restaurant",
        "식이 옵션": "Dietary options",
        "아이콘": "Icon",
        "알 수 없는 오류": "Unknown error",
        "알림": "Notice",
        "연결 안 됨": "Not Connected",
        "연락처": "Contact",
        "영업 정보": "Business Info",
        "영업시간": "Hours",
        "영업시간 (예: 09:00-18:00)": "Hours (e.g. 09:00-18:00)",
        "영업시간(홈페이지): ": "Hours (from homepage): ",
        "예약": "Reserve",
        "예약 ": "Reservation ",
        "예약 방법": "Reservation method",
        "예약 방법 (예: 캐치테이블 예약)": "Reservation method (e.g. Catch Table booking)",
        "완료": "Done",
        "기기 간 동기화": "Sync Across Devices",
        "준비 중…": "Preparing…",
        "iCloud와 맞추기": "Sync with iCloud",
        "지금 맞추기": "Sync Now",
        "받는 중…": "Receiving…",
        "동기화": "Sync",
        "장 받음": " received",
        "장 올림": " uploaded",
        "사진을 주고받지 못했습니다(장소는 끝났습니다): ": "Could not sync photos (places are done): ",
        "iCloud에서 자료를 다 받지 못했습니다.": "Could not receive all of your data from iCloud.",
        "개 추가": " added",
        "개 갱신": " updated",
        "개 지움": " removed",
        "개 올림": " uploaded",
        "지금 맞추기는 다른 기기에서 올린 게시판과 장소를 먼저 받아 합친 뒤, 합친 결과를 본인 iCloud에 올립니다. 이 기기에 없던 장소는 추가하고, 다른 기기에서 더 나중에 고친 장소는 그 내용으로 바꾸며, iCloud에 없는 장소는 그대로 둡니다. 한 기기에서 아주 지운 장소는 다른 기기에서도 지워지고 다시 살아나지 않습니다. 사진은 장소가 가리키는 것만, 아직 없는 쪽으로만 오갑니다.": "Sync Now first receives the boards and places other devices uploaded and merges them in, then uploads the merged result to your own iCloud. Places this device did not have are added, places edited more recently on another device are replaced with that version, and places not in iCloud are left alone. A place deleted for good on one device is deleted on the others too and never comes back. Only photos your places refer to are synced, and only in the direction that is missing one.",
        "iCloud 연결을 먼저 확인해주세요.": "Check the iCloud connection first.",
        "확인 안 함": "Not checked",
        "확인 중…": "Checking…",
        "연결됨 (": "Connected (",
        "iCloud에 로그인되어 있지 않습니다.": "You are not signed in to iCloud.",
        "이 기기에서 iCloud가 제한되어 있습니다.": "iCloud is restricted on this device.",
        "iCloud 상태를 확인하지 못했습니다.": "Could not determine the iCloud status.",
        "iCloud를 일시적으로 쓸 수 없습니다.": "iCloud is temporarily unavailable.",
        "알 수 없는 iCloud 상태입니다.": "Unknown iCloud status.",
        "iCloud 사용자 정보를 받지 못했습니다.": "Could not get your iCloud account information.",
        "보드 순서": "Board Order",
        "보드 순서 바꾸기": "Reorder Boards",
        "외부 링크": "External links",
        "요일": "Day",
        "요청 시간이 초과되었습니다.": "The request timed out.",
        "웹사이트": "Website",
        "웹사이트 URL": "Website URL",
        "위 \"방문함\"과 별개로, 실제로 방문한 날짜들을 기록해둡니다.": "Separate from \"Visited\" above — keeps a record of the actual dates you visited.",
        "위 항목 어디에도 맞지 않는 정보를 자유롭게 적어두는 곳입니다.": "A free-form spot for anything that doesn't fit the fields above.",
        "위도": "Latitude",
        "위치 권한이 꺼져 있습니다": "Location Permission Is Off",
        "위치정보에 사진 GPS 사용": "Use Photo GPS for Location Info",
        "유효하지 않은 API 키입니다.": "That API key isn't valid.",
        "의 호출 한도를 초과했습니다. 잠시 후 다시 시도해주세요.": "'s call limit was exceeded. Please try again shortly.",
        "이 링크에서 장소 정보를 아직 찾지 못했습니다. 아래 검색을 다시 눌러보거나, 장소명을 직접 입력해주세요.": "No place info could be recovered from this link yet. Try the search below again, or type the place name yourself.",
        "이 사진을 삭제할까요?": "Delete this photo?",
        "이 기기 이름": "This Device's Name",
        "이름·주소로 검색해 실제 장소를 찾아 고르면, 검증된 정보로 갱신하고 이후 \"Google/Naver에서 새로고침\"도 쓸 수 있게 됩니다. Google → Naver → Apple 순으로 시도하고, 키가 없어도 Apple은 항상 됩니다.":
            "Search by name/address and pick the actual place to update it with verified info — and unlock \"Refresh from Google/Naver\" afterward. Tries Google, then Naver, then Apple — Apple always works even with no key registered.",
        "이 카드에 추가할까요?": "Add to this card?",
        "이 폴더에 대한 접근 권한이 끊어졌습니다. 아래에서 폴더를 다시 선택해주세요.": "Access to this folder was lost. Please choose the folder again below.",
        "이름": "Name",
        "이름 (예: 도쿄 봄 여행)": "Name (e.g. Tokyo Spring Trip)",
        "이름은 유지": "Keep the Name",
        "이름이 같고 위치나 주소가 가까워야 중복으로 표시됩니다.": "Shown as a duplicate only when the name matches and the location or address is close.",
        "이름이 다릅니다": "Name Doesn't Match",
        "이미지를 처리할 수 없습니다.": "Couldn't process the image.",
        "이미지에서 장소를 찾지 못했습니다. 다른 사진으로 다시 시도해주세요.": "No places were found in the image. Please try again with different photos.",
        "PinSpots 백업 파일도, Google Takeout 파일도 아닙니다.": "Not a PinSpots backup file or a Google Takeout file.",
        "PinSpots 백업 파일과 Google Takeout의 저장한 장소(Saved Places.json, 목록별 CSV)를 모두 읽습니다.": "Reads both a PinSpots backup file and Google Takeout saved places (Saved Places.json, or a CSV per list).",
        "Google Takeout에서 읽었습니다. 이름·주소(있으면 좌표)만 담기며, 평점·사진·영업시간은 조회하지 않습니다 — 나중에 카드를 열어 채울 수 있습니다. 기존 게시판·장소는 그대로 둡니다.": "Read from Google Takeout. Only the name, address and — where the file has one — the coordinate come across; no rating, photo or opening hours are looked up, so nothing is spent on places you never open. Your existing boards and places are left alone.",
        "내 평점": "My rating",
        "라스트오더": "Last order",
        "수상": "Awards",
        "방문": "Visited",
        "재방문 의향": "Would revisit",
        "추가한 날짜": "Date added",
        "CSV로 내보내기": "Export as CSV",
        "CSV로 공유": "Share as CSV",
        "CSV를 저장했습니다.": "Saved the CSV.",
        "CSV를 저장하지 못했습니다.": "Couldn't save the CSV.",
        "방문으로 표시": "Mark as visited",
        "방문 표시 해제": "Unmark as visited",
        "즐겨찾기에 추가": "Add to favorites",
        "즐겨찾기 해제": "Remove from favorites",
        "전화 걸기": "Call",
        "웹사이트 열기": "Open website",
        "인스타그램 열기": "Open Instagram",
        "선택 해제": "Deselect",
        "선택됨": "Selected",
        "목록으로 보기": "Show as list",
        "격자로 보기": "Show as grid",
        "더 보기": "More",
        "태그 삭제": "Remove tag",
        "사진 빼기": "Remove photo",
        "기존 카테고리에서 고르기": "Choose from existing categories",
        "위로 이동": "Move up",
        "아래로 이동": "Move down",
        "표지 아이콘": "Cover icon",
        "설정에서 Google Places API 키를 등록하면 평점·사진·영업시간도 함께 채웁니다.": "Register a Google Places API key in Settings to fill in the rating, photo and opening hours too.",
        "사진에서 주소를 찾지 못했습니다. 기기 내 읽기는 가게 이름과 주소가 함께 보이는 사진에서만 동작합니다. 주소가 없는 목록 이미지는 설정에서 AI 키를 등록하면 읽을 수 있습니다.": "Couldn't find an address in the photo. Reading on this device only works on a photo that shows a place's name and its address together. For a list image with no addresses, register an AI key in Settings.",
        "나머지 ": "The other ",
        "곳은 목록에서 직접 검색할 수 있습니다.": " can be searched from the list yourself.",
        "기기에서 글자를 읽어 장소 이름과 주소를 찾았습니다. 나머지 정보는 Google 확인으로 채워집니다.": "Found a place name and address by reading the text on this device. The rest is filled in by verifying against Google.",
        "사진에서 읽은 이름·주소를 채웠습니다.": "Filled in the name and address read from the photo.",
        "사진에서 장소 찾기 (": "Find places in photos (",
        "사진에서 찾기": "Find it in a photo",
        "사진 앱에 담기": "Save to Photos",
        "사진 앱에 담을까요?": "Save to Photos?",
        "담기": "Save",
        "사진 앱의 PinSpots 앨범에 이 카드의 사진을 전부 담습니다. 한 장만 담으려면 사진을 눌러 크게 연 뒤 오른쪽 위 메뉴를 쓰세요. 사진 앱에서 고른 사진이었다면 라이브러리에 한 장 더 생깁니다. 사진 앱의 앨범 → 유틸리티 → 중복 항목에서 병합하면 원본과 하나로 합쳐지고, 그 원본이 PinSpots 앨범에 남습니다.": "Adds all of this card's photos to a PinSpots album in Photos. To save just one, tap a photo to open it full screen and use the menu at the top right. For a photo you originally picked from Photos, this creates one more copy in your library. In Photos, go to Albums → Utilities → Duplicates and merge: the two become one, and that original is what stays in the PinSpots album.",
        "사진 앱의 PinSpots 앨범에 이 사진 한 장을 담습니다. 사진 앱에서 고른 사진이었다면 라이브러리에 한 장 더 생깁니다. 사진 앱의 앨범 → 유틸리티 → 중복 항목에서 병합하면 원본과 하나로 합쳐지고, 그 원본이 PinSpots 앨범에 남습니다.": "Adds this one photo to a PinSpots album in Photos. For a photo you originally picked from Photos, this creates one more copy in your library. In Photos, go to Albums → Utilities → Duplicates and merge: the two become one, and that original is what stays in the PinSpots album.",
        "담을 사진이 없습니다.": "There are no photos to save.",
        "사진 앱의 PinSpots 앨범에 ": "Saved ",
        "장을 담았습니다.": " photo(s) to the PinSpots album in Photos.",
        "사진 접근이 꺼져 있어 담지 못했습니다. 설정에서 켜주세요.": "Photos access is off, so nothing was saved. Turn it on in Settings.",
        "사진 파일을 읽지 못했습니다.": "Could not read the photo files.",
        "사진 앱에 앨범을 만들지 못했습니다.": "Could not create the album in Photos.",
        "사진 앱에 저장하지 못했습니다.": "Could not save to Photos.",
        "지도 앱 스크린샷은 AI 키 없이 기기에서 바로 인식합니다. 설정에서 AI 키를 등록하면 인스타그램 게시물처럼 복잡한 사진도 읽을 수 있습니다.": "Map app screenshots are recognized right on this device, no AI key needed. Register an AI key in Settings to also read busier photos like Instagram posts.",
        "\"지도에서 열기\"로 최근에 연 카드예요. 방금 공유한 사진을 이 카드에 추가하고, 기기에서 글자를 읽어 비어 있는 이름·주소를 채웁니다. (설정에서 AI 키를 등록하면 전화번호·영업시간 등도 함께 읽습니다.)": "This is the card you most recently opened with \"Open in Maps\". The photo you just shared is added to it, and the text on it is read on this device to fill in a blank name or address. (Register an AI key in Settings to read the phone number, opening hours and more as well.)",
        "인스타그램": "Instagram",
        "인스타그램 URL": "Instagram URL",
        "인스타그램 링크는 자동으로 인식할 수 없어요": "Instagram links can't be recognized automatically",
        "인스타그램 스크린샷": "Instagram screenshot",
        "읽을 수 없는 텍스트입니다.": "Couldn't read that text.",
        "입력 오류: ": "Input error: ",
        "입장료": "Admission fee",
        "입장료 ": "Admission fee: ",
        "입장료 (예: 성인 15,000원)": "Admission fee (e.g. 15,000 won for adults)",
        "자동 백업 끄기": "Turn Off Auto Backup",
        "자동으로 백업": "Back Up Automatically",
        "잘못된 검색어입니다.": "Invalid search query.",
        "잘못된 사진 URL": "Invalid photo URL",
        "장)": " photos)",
        "장소 ": "",
        "장소 검색": "Search places",
        "장소 선택…": "Choose a Place…",
        "장소 정보 수정": "Edit Place Info",
        "장소 추가": "Add Place",
        "장소 확정": "Confirm Place",
        "장소명": "Place name",
        "장소를 확정했습니다.": "Place confirmed.",
        "장소확정": "Confirmed",
        "저장": "Save",
        "저장 실패 (코드 ": "Save failed (code ",
        "저장된 데이터 일부를 읽지 못했습니다. 원본 파일은 \"": "Some of your saved data couldn't be read. The original file has been kept as \"",
        "저장된 데이터를 읽지 못했습니다": "Couldn't Read Saved Data",
        "저장 실패: ": "Save failed: ",
        "전달받은 사진": "Received Photo",
        "전체": "All",
        "전체 (": "All (",
        "전체 백업": "Full Backup",
        "전체 보기": "Show All",
        "전체 선택": "Select All",
        "전체 해제": "Deselect All",
        "전화": "Call",
        "전화번호": "Phone",
        "전화번호: ": "Phone: ",
        "정렬: ": "Sort: ",
        "정보": "Info",
        "제안된 태그: ": "Suggested tags: ",
        "좌표": "Coordinates",
        "좌표를 확인했습니다.": "Coordinates confirmed.",
        "주기": "Frequency",
        "주소": "Address",
        "주소 링크 공유": "Address link share",
        "주소로 좌표 확인": "Find Coordinates from Address",
        "주소로 좌표를 찾지 못했습니다.": "Couldn't find coordinates for that address.",
        "중복 찾기": "Find Duplicates",
        "중복이 없습니다": "No Duplicates",
        "즐겨찾기": "Favorite",
        "지금 백업": "Back Up Now",
        "지도": "Map",
        "지도 링크 가져오기": "Import Map Link",
        "지도 링크의 좌표를 카드에 저장했습니다.": "Saved the map link's coordinates on the card.",
        "지도 앱, SNS, 직접 찍은 사진에서 발견한 장소를 하나의 카드로 모아보세요.": "Gather places you found in map apps, social media, or photos you took, into a single card.",
        "지도에서 보기": "View on Map",
        "지도에서 열기": "Open in Map",
        "지도에서 장소 확인": "Confirm Place on Map",
        "지도에서 찾기": "Look Up on Map",
        "직접 입력": "Enter manually",
        "직접 입력…": "Enter manually…",
        "찾아낸 중복을 모두 병합했습니다.": "All the duplicates found have been merged.",
        "첫 게시판 만들기": "Create First Board",
        "추가": "Add",
        "추가 (": "Add (",
        "추가하기": "Add",
        "추가한 사진이 이 장소에서 촬영된 것 같지 않습니다 (사진 GPS가 주소에서 100m 이상 떨어져 있습니다).":
            "The photo you added doesn't look like it was taken at this place (its GPS is more than 100m from the address).",
        "추가할 게시판": "Board to add to",
        "추가할 장소 (": "Places to add (",
        "추천 메뉴": "Recommended menu",
        "추천 메뉴 ": "Recommended menu: ",
        "추천 소요 시간": "Suggested duration",
        "추천 소요 시간 ": "Suggested duration: ",
        "추천 소요 시간 (예: 1~2시간)": "Suggested duration (e.g. 1-2 hours)",
        "취소": "Cancel",
        "카드 보기": "View Card",
        "카카오맵 공유": "Kakao Map share",
        "카카오맵": "Kakao Map",
        "카카오맵 스크린샷": "Kakao Map screenshot",
        "카테고리": "Category",
        "카테고리 변경": "Change Category",
        "카테고리 이름": "Category Name",
        "카테고리 입력": "Enter Category",
        "카테고리: ": "Category: ",
        "카페": "Cafe",
        "켜두면 카드에 아직 좌표가 없을 때 이 사진의 GPS를 좌표로 저장합니다(주소와 100m 이상 차이 나면 저장하지 않고 알려드립니다). 카드에 이미 좌표가 있으면 이 사진이 그 위치에서 찍힌 게 맞는지만 확인합니다.":
            "When on, if the card has no coordinates yet, this photo's GPS is saved as the coordinates (unless it's more than 100m from the address, in which case you're told and nothing is saved). If the card already has coordinates, this only checks whether the photo looks like it was actually taken there.",
        "키체인 오류: ": "Keychain error: ",
        "태그": "Tag",
        "태그 추가": "Add tag",
        "태그: ": "Tags: ",
        "특정 예약 플랫폼으로 바로 연결되는 링크는 지원하지 않아, 상세보기의 \"예약\" 버튼은 여기 적은 내용으로 웹 검색을 열어줍니다.": "Direct links to a specific reservation platform aren't supported — the detail view's \"Reserve\" button opens a web search for whatever you write here instead.",
        "텍스트 붙여넣기": "Paste Text",
        "텍스트로 복사": "Copy as Text",
        "파일 선택…": "Choose File…",
        "파일 이름": "File Name",
        "파일로 공유": "Share as File",
        "파일을 읽지 못했습니다.": "Couldn't read the file.",
        "편의시설": "Amenities",
        "편집": "Edit",
        "플랫폼 (예: Trip Advisor)": "Platform (e.g. Trip Advisor)",
        "평가": "Rating",
        "평점": "Rating",
        "평점 (0~5)": "Rating (0-5)",
        "폴더": "Folder",
        "폴더를 한 번 선택해두면, 앱을 열거나 닫을 때마다(위 주기당 최대 한 번) PinSpots가 그 폴더에 새 백업을 저장합니다.": "Pick a folder once and PinSpots writes a fresh backup into it whenever the app opens or closes — at most once per the interval above.",
        "백업 파일 이름에 들어가, 여러 기기가 같은 폴더에 백업할 때 어느 기기가 만든 파일인지 알 수 있게 합니다. 비워두면 iOS가 알려주는 이름을 쓰는데, iOS 16부터 그건 설정에서 지어준 이름이 아니라 기종 이름(“iPhone”)이라 같은 기종 둘은 구별되지 않습니다. 짧을수록 좋습니다. 설정의 “전체 백업” 파일에도 함께 적용됩니다.":
            "Goes into the backup's filename, so you can tell which device wrote which file when several back up to the same folder. Leave it blank and the name iOS reports is used — but since iOS 16 that is the model name (“iPhone”), not the name you gave the device, so two of the same model are indistinguishable. Shorter is better. It applies to the “Full Backup” file in Settings as well.",
        "폴더 변경…": "Change Folder…",
        "폴더에 쓰지 못했습니다 — 아래에서 폴더를 다시 선택해주세요.": "Couldn't write to the folder — please choose the folder again below.",
        "현장 촬영": "Taken on-site",
        "현재 위치": "Current Location",
        "현재 위치를 가져오지 못했습니다": "Couldn't get your current location",
        "현재 위치에서의 거리를 표시하려면 설정 앱에서 PinSpots의 위치 권한을 허용해주세요.": "To show distance from your current location, allow location access for PinSpots in the Settings app.",
        "호텔": "Hotel",
        "홈": "Home",
        "확인": "OK",
        "휴무일": "Closed on",
        "휴무일 ": "Closed on ",
        " · ": " · ",
        "AI 요청": "AI requests",
        "API별 일일 할당량을 직접 거세요": "Set a daily quota for each API",
        "Cloud Console → APIs & Services → Places API (New) → Quotas & System Limits에서 메서드별로 설정합니다. 기본값이 수십만 회라 그대로 두면 노출 금액이 큽니다.\n\n• SearchTextRequest — 200 (장소 검색과 주소 변환이 함께 소비)\n• GetPlaceRequest — 50\n• GetPhotoMediaRequest — 200\n• AutocompletePlacesRequest — 0 (미사용)\n• SearchNearbyRequest — 0 (미사용)\n• SearchMediaRequest — 0 (미사용)\n• SearchReviewPostsRequest — 0 (미사용)\n• Maps JavaScript API → Map loads per day — 200": "Set these per method under Cloud Console → APIs & Services → Places API (New) → Quotas & System Limits. The defaults run to hundreds of thousands of calls, so leaving them alone leaves a lot exposed.\n\n• SearchTextRequest — 200 (place lookup and address conversion share this one)\n• GetPlaceRequest — 50\n• GetPhotoMediaRequest — 200\n• AutocompletePlacesRequest — 0 (unused)\n• SearchNearbyRequest — 0 (unused)\n• SearchMediaRequest — 0 (unused)\n• SearchReviewPostsRequest — 0 (unused)\n• Maps JavaScript API → Map loads per day — 200",
        "Geocoding API는 켜지 않아도 됩니다": "You don't need the Geocoding API",
        "Google 사진": "Google photos",
        "Google 장소 검색": "Google place search",
        "Google 장소 상세": "Google place details",
        "Google 키 설정 방법": "Setting Up the Google Key",
        "Naver 연동": "Naver",
        "REST 호출은 번들 ID로, 웹뷰의 지도는 리퍼러로 확인되는데 키 하나에는 제한을 한 종류만 걸 수 있습니다. \"iOS 앱\"을 고르면 지도 탭이 백지가 됩니다. 대신 아래 할당량으로 사용량을 막는 것을 권합니다.": "REST calls are checked by bundle ID and the map in the web view by referer, but a key carries only one kind of restriction. Choosing \"iOS apps\" blanks out the map tab. Hold usage down with the quotas below instead.",
        "iCloud에 보관된 사본을 삭제했습니다.": "Deleted the copy stored in iCloud.",
        "iCloud에 자동 보관": "Keep a copy in iCloud",
        "개 등록됨": " registered",
        "개인정보 및 약관": "Privacy and Terms",
        "개인정보 처리방침": "Privacy Policy",
        "검색": "Search",
        "기록 지우기": "Clear counts",
        "기기 이름": "Device Name",
        "네이버 지도에서 공유받은 장소는 Google 대신 이 API로 검증합니다. 위 \"지도 표시\"와는 별개의 애플리케이션입니다 — NAVER Cloud Platform 콘솔에서 Menu → All Services → Application Services → NAVER API HUB로 들어가 Application을 등록할 때 \"검색\" API를 선택하고, 등록된 Application의 \"인증 정보\"에서 Client ID/Secret을 확인해 입력하세요. 설정하지 않으면 지금처럼 Google로 검증합니다.": "Places shared from Naver Map are verified against this API instead of Google. It is a separate application from \"Map display\" above — in the NAVER Cloud Platform console, go to Menu → All Services → Application Services → NAVER API HUB, select the \"Search\" API when registering an application, then copy the Client ID and Secret from that application's credentials. Leave it unset and verification keeps going through Google as it does now.",
        "다른 앱에서 공유한 사진을 받아올 수 없는 상태입니다. 앱을 다시 설치해도 계속되면 알려주세요.": "Photos shared from other apps can't be received right now. If reinstalling the app doesn't fix it, please get in touch.",
        "두 개의 API를 모두 켜야 합니다": "Both APIs have to be enabled",
        "미설정": "Not set",
        "사용량": "Usage",
        "사진 스캔을 실행하면 선택한 이미지가 아래에서 등록한 제공자에게 업로드됩니다. 업로드된 이미지의 처리·보관은 각 제공자의 정책을 따릅니다. 스캔을 실행하지 않으면 사진은 기기를 떠나지 않습니다.": "Running a photo scan uploads the selected image to whichever provider you register below. How that image is handled and retained is governed by that provider's own policy. If you never run a scan, your photos never leave this device.",
        "애플리케이션 제한은 \"없음\"으로 두세요": "Leave the application restriction set to \"None\"",
        "여러 제공자의 키를 등록해두면, 아래 순서대로 시도하다가 하나가 실패(호출 한도 초과, 오류 등)해도 자동으로 다음 제공자로 넘어갑니다.": "Register keys for more than one provider and the app tries them in the order below, moving on to the next automatically when one fails (rate limit, error, and so on).",
        "예산 알림을 함께 걸어두세요": "Set a budget alert as well",
        "오늘 ": "Today ",
        "우선순위": "Priority",
        "이 기기가 보낸 Google Places와 AI 요청 수입니다. 오늘 수치 뒤의 숫자는 이 앱이 권장하는 일일 할당량이며, 실제로 설정된 할당량이 아닙니다. 요금은 각 제공자가 사용자 계정에 직접 청구하므로 실제 금액은 해당 콘솔에서 확인하세요.": "How many Google Places and AI requests this device has sent. The number after today's count is the daily quota this app recommends, not the one actually configured on your account. Each provider bills you directly, so check the real amount in their console.",
        "이번 달 ": "this month ",
        "이용약관": "Terms of Service",
        "장소 검색·상세·사진은 Places API (New)를 호출하고, \"지도\" 탭의 Google 지도는 Maps JavaScript API를 웹뷰에 띄워 그립니다. 같은 키를 쓰지만 서로 다른 API라서, 하나만 켜면 다른 쪽이 조용히 동작하지 않습니다.": "Place search, details and photos call the Places API (New), while the Google map in the \"Map\" tab is the Maps JavaScript API loaded into a web view. They use the same key but are different APIs, so enabling only one leaves the other quietly not working.",
        "장소 검증": "Place verification",
        "장소 확인과 평점·사진·영업시간 채우기, 그리고 \"지도\" 탭의 Google 지도에 사용됩니다. 키가 없어도 공유로 장소를 담고 기기 내 사진 읽기를 쓸 수 있지만, 그 정보들은 비어 있게 됩니다.": "Used to confirm a place, fill in its rating, photo and hours, and draw the Google map in the \"Map\" tab. Without a key you can still save places by sharing and read photos on-device, but those fields stay empty.",
        "제3자가 운영하는 게이트웨이입니다.": "A gateway operated by a third party.",
        "제공자 키 (BYOK)": "Provider Keys (BYOK)",
        "주소를 좌표로 바꾸는 것도 Places의 searchText가 처리합니다. 별도로 켜면 할당량 없는 표면만 하나 늘어납니다.": "Turning an address into coordinates is handled by Places' own searchText. Enabling it separately just adds one more surface with no quota on it.",
        "지도 · 검색": "Map · Search",
        "지도 표시": "Map display",
        "최종 수정: ": "Last updated: ",
        "키 발급과 설정 방법": "How to get and set up a key",
        "키 유출에 대한 방어가 제한이 아니라 할당량이므로, 결제 계정의 예산 알림(예: $5에 50/90/100%)이 사실상 마지막 안전망입니다.": "Since a leaked key is held back by quotas rather than by a restriction, a budget alert on the billing account (say $5, at 50/90/100%) is effectively the last line of defence.",
        "폴더 자동 백업": "Scheduled Folder Backup",
        "AI 사진 읽기 — 가장 먼저 설정하세요": "AI Photo Reading — Set This Up First",
        "AI 제공자": "AI Providers",
        "AI 키를 등록하면 인스타그램 게시물처럼 주소가 없는 사진에서도 장소를 읽고 전화번호·영업시간까지 채웁니다. 등록하지 않으면 가게 이름과 주소가 함께 보이는 사진만 읽을 수 있습니다. 키는 이 기기의 키체인에만 저장됩니다.": "Register an AI key and the app reads places out of photos with no address in them, such as an Instagram post, filling in phone numbers and opening hours too. Without one, only photos showing a business name alongside its address can be read. Your key is kept in this device's Keychain and nowhere else.",
        "Google — 지도와 장소 정보": "Google — Maps and Place Information",
        "Naver — 한국 장소 (선택)": "Naver — Korean Places (Optional)",
        "네이버 지도에서 공유받은 장소를 Google 대신 Naver로 검증하고, \"지도\" 탭에 네이버 지도를 띄울 수 있습니다. 설정하지 않아도 모든 장소는 Google로 검증됩니다.": "Verifies places shared from Naver Map against Naver instead of Google, and lets the \"Map\" tab show a Naver map. Leave it unset and every place is verified through Google.",
        "다른 제공자와 우선순위": "Other Providers and Priority",
        "사진 스캔으로 채워지는 카테고리·메모 같은 정보를 어떤 언어로 가져올지 정합니다. 앱 화면 자체의 언어는 iOS 설정의 언어를 따릅니다.": "Sets the language that information read from photos — a category, a note — comes back in. The app's own screens follow the language set in iOS.",
        "언어": "Language",
        "이 앱의 핵심은 사진에서 장소를 찾아내는 것이고, 그 일을 하는 것이 이 키입니다. 등록하면 인스타그램 게시물처럼 주소가 없는 사진에서도 장소를 읽고 전화번호·영업시간까지 채웁니다. 등록하지 않으면 가게 이름과 주소가 함께 보이는 사진만 기기에서 읽을 수 있고, 그 외의 사진에서는 아무것도 얻지 못합니다.": "This app is about finding places in photos, and this key is what does that. Register one and it reads places out of photos with no address in them, such as an Instagram post, filling in phone numbers and opening hours too. Without one, only photos showing a business name alongside its address can be read on this device, and anything else yields nothing at all.",
        "읽어오는 언어": "Language of results",
        "제공자": "Provider",
        "키를 등록하지 않으면 기능이 크게 제한됩니다.": "Without a key, this app can do much less.",

        // MARK: - 온보딩
        "Google 지도나 네이버 지도에서 장소를 공유하면 바로 카드가 됩니다. 키 없이도 이름·주소·위치는 그대로 담기고, Google 키를 등록하면 평점·사진·영업시간까지 채워집니다.": "Share a place from Google Maps or Naver Map and it becomes a card right away. The name, address and location are kept even with no key at all; register a Google key and ratings, photos and opening hours get filled in too.",

        // MARK: - 직접 입력 / 게시판 선택
        "+ 직접 입력": "+ Enter manually",
        "사진을 고르면 AI가 장소를 찾아주고, \"직접 입력\"으로 이름을 직접 적을 수도 있습니다.": "Pick a photo and AI finds the places in it, or use \"Enter manually\" to type a name yourself.",
        "어느 게시판에 담을까요?": "Which board?",
        "게시판이 먼저 필요합니다": "A board comes first",
        "장소 카드는 게시판 안에 담깁니다. 홈 탭에서 게시판을 먼저 만들어주세요.": "Place cards live inside a board. Create one in the Home tab first.",
        "개 장소": " places",

        // MARK: - 지도 빈 상태 / Naver 제외 안내
        "지도에 표시할 장소가 없습니다": "Nothing to show on the map",
        "아직 저장된 장소가 없습니다. 갤러리 탭의 \"장소 추가\"로 첫 장소를 담아보세요.": "No places saved yet. Use \"Add Place\" in the Gallery tab to save your first one.",
        "검색어와 일치하는 장소가 없습니다.": "No places match your search.",
        "저장된 장소에 아직 좌표가 없습니다. 카드 편집의 \"주소로 좌표 확인\"으로 좌표를 채우면 지도에 표시됩니다.": "None of your saved places have coordinates yet. Fill them in with \"Find Coordinates from Address\" when editing a card and they will appear here.",
        "Naver 지도에 표시할 한국 장소가 없습니다": "No Korean places to show on the Naver map",
        "Naver 지도는 한국 내 장소만 표시합니다. 한국 밖 장소는 Apple이나 Google 지도로 보실 수 있습니다.": "Naver's map only shows places inside Korea. For places elsewhere, use the Apple or Google map.",
        "\"을(를) 완전히 지울까요?": "\" — delete permanently?",
        "가져오기에서만 제거": "Remove from Import Only",
        "개 완전 삭제": " selected — Delete Completely",
        "게시판에 추가": "Add to Board",
        "게시판에서 제거": "Remove from Board",
        "보드": "Boards",
        "보드에 추가": "Add to Board",
        "어느 보드에도 없습니다": "Not in any board",
        "보드에서 빼기": "Remove from board",
        "한국 밖 ": "Outside Korea, ",
        "곳은 Naver 지도에 표시되지 않습니다.": " place(s) are not shown on the Naver map.",

        // MARK: - 저장 공간
        "저장 공간": "Storage",
        "계산 중…": "Calculating…",
        "고른 것이 없습니다": "Nothing Selected",
        "공유한 링크": "Shared Link",
        "되돌리기": "Restore",
        "비우기": "Empty",
        "사진까지 함께 지워지며 되돌릴 수 없습니다.": "Its photos are deleted too, and this cannot be undone.",
        "삭제 ": "Deleted ",
        "삭제됨": "Deleted",
        "삭제됨으로 옮겨집니다. 거기서 되돌릴 수 있습니다.": "Moved to Deleted, where it can be restored.",
        "삭제됨을 비울까요?": "Empty Deleted?",
        "삭제됨의 카드는 ": "Cards in Deleted are erased after ",
        "삭제됨이 비어 있습니다": "Deleted is Empty",
        "여기서만 빼면 카드는 다른 곳에 그대로 남습니다.": "Removing it here leaves the card everywhere else.",
        "완전 삭제": "Delete Completely",
        "완전 삭제는 삭제됨으로 옮겨지고 거기서 되돌릴 수 있습니다.": "Deleting completely moves it to Deleted, where it can be restored.",
        "왼쪽에서 게시판이나 모음을 고르세요.": "Pick a board or collection on the left.",
        "이 게시판에서만 제거": "Remove from This Board Only",
        "이 카테고리를 단 카드가 모두 새 이름으로 바뀝니다.": "Every card with this category takes the new name.",
        "이름 바꾸기": "Rename",
        "일 뒤 저절로 지워집니다.": " days.",
        "장의 사진": " photos",
        "지우기": "Delete",
        "카테고리 편집": "Edit Categories",
    ]
}
